fix: MSVC defines + lpp_exec typo + rustfmt
runtime/windows_x86_64_min.c: add missing defines
  - #define TRUE 1 / FALSE 0 / STARTF_USESTDHANDLES 0x100 / CREATE_NO_WINDOW 0x08000000
  These were used in command_exec/command_output but only defined
  implicitly by windows.h which we don't include (freestanding).

runtime/lpp_exec.c: fix strcpy(cmdline)(cmdline) typo on lines 30 and 56
  MSVC error C2064: term does not evaluate to a function taking 1 argument

Full rustfmt pass on all Rust source files.